In [52]:
import matplotlib.pylab as plt
from numpy import *

def createDataSet():
    group = array([[1.0, 1.1],
                   [1.0, 1.0],
                   [0, 0],
                   [0, 0.1]])
    labels = ['A', 'A', 'B', 'B']
    return group, labels

def classify0(inX, dataSet, labels, k):
    dataSetSize = dataSet.shape[0]
    diffMat = tile(inX, (dataSetSize, 1)) - dataSet
    sqDiffMat = diffMat ** 2
    sqDistances = sqDiffMat.sum(axis=1)
    distance = sqDistances ** 0.5
    sortedDistIndices = distance.argsort()
    classCount = {}
    for i in range(k):
        voteIlabel = labels[sortedDistIndices[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel, 0) + 1
    sortedClassCount = sorted(classCount.iteritems(),
                              key=operator.itemgetter(1),
                              reverse=True)
    return sortedClassCount[0][0]
group, labels = createDataSet()
classify0([0, 0], group, labels, 3)

def file2matrix(filename):
    fr = open(filename)
    arrayLines = fr.readlines()
    numberOfLines = len(arrayLines)
    returnMat = zeros((numberOfLines, 3))
    classLabelVector = []
    index = 0
    for line in arrayLines:
        listForLine = line.split('\t')
        returnMat[index, :] = listForLine[:-1]
        classLabelVector.append(int(listForLine[-1]))
        index += 1
    return returnMat, classLabelVector
datingDateMat, datingLabels = file2matrix('C:\Users\Administrator\Desktop\python-learn\ML\datingTestSet2.txt')
# fig = plt.figure()
# ax = fig.add_subplot(111)
# ax.scatter(datingDateMat[:, 1], datingDateMat[:, 2], 15.0 * array(datingLabels), 15.0 * array(datingLabels))
# plt.show()

def autoNorm(dataSet):
    minVals = dataSet.min(0)
    maxVals = dataSet.max(0)
    ranges = maxVals - minVals
    normDataSet = zeros(shape(dataSet))
    m = dataSet.shape[0]
    normDataSet = dataSet - tile(minVals, (m, 1))
    normDataSet = normDataSet / tile(ranges, (m, 1))
    return normDataSet, ranges, minVals
normMat, ranges, minVals = autoNorm(datingDateMat)


array([0.      , 0.      , 0.001156])

In [22]:
# coding=utf-8

dataSet, labels = createDataSet()
inX = [0, 0]
dataSetSize = dataSet.shape[0]
diffMat = tile(inX, (dataSetSize, 1)) \
          - dataSet
sqDiffMat = diffMat ** 2
sqDistances = sqDiffMat.sum(axis=1)
distance = sqDistances ** 0.5
sortedDistIndices = distance.argsort()  # 从小到大的索引
sortedDistIndices


array([2, 3, 1, 0], dtype=int64)

In [23]:
distance

array([1.48660687, 1.41421356, 0.        , 0.1       ])

In [18]:
sqDistances

array([2.21, 2.  , 0.  , 0.01])