In [3]:
import time

# print time.ctime()
# print 'hello jupyter'
import numpy as np

a = np.array([
    [
        [3.4, 5, 6, 8],
        [3, 2.4, 5, 7]
    ],
    [
        [2.3, 4, 5, 6],
        [0.9, 5, 6, 1]
    ],
    [
        [9, 6.7, 3, 2],
        [1, 3, 4, 5]
    ]
])
a.ndim
a.dtype

a.shape

a.size

1 / 2.0 / 3 / 4 / 5

In
a = np.array([1, 2, 3])
a

type(a)
a.dtype
a.ndim
a.size
a.shape
b = np.array([[1.3, 2.4], [0.3, 4.1]])
b.dtype

b.ndim
b.size
b.shape
b.itemsize
g = np.array([
    ['a', 'b'],
    ['c', 'd']
])
g

g.dtype
g.dtype.name
f = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=complex)
f

np.zeros((3, 3))

np.ones((3, 3))
np.arange(0, 10, 2.1)

b = np.arange(4, 8)
b
a
a = np.arange(4)
a + b
a - b

a * b

a * np.sin(b)

A = np.arange(0, 9).reshape(3, 3)
A
B = np.ones((3, 3))
B
A * B
np.dot(A, B)

a += 1
a
a
a = np.arange(0, 4)
a
a += 1
a
a -= 1
a
a = np.arange(1, 5)
a
np.sqrt(a)
np.log(a)
np.sin(a)
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
a.sum()
a.max()
a.mean()
a.std()
a = np.arange(10, 16)
a
a[4]
a[-1]
a[[1, 3, 4]]

A = np.arange(10, 18).reshape((2, 4))
A
A[1, 2]

a = np.arange(10, 16)
a
a[1:5]
a[1:5:2]
A = np.arange(10, 19).reshape((3, 3))
A
A[0, :]

A[:, 0]

A[:2, :2]

A[1]
A[1,]

A[[0, 1],]

A[[0, 2], 0:2]

A
a = np.arange(10, 16)
for i in a:
    print i


10
11
12
13
14
15


In [4]:
for row in A:
    print row

[10 11 12]
[13 14 15]
[16 17 18]


In [5]:
for item in A.flat:
    print item

10
11
12
13
14
15
16
17
18


In [6]:
np.apply_along_axis(np.mean, axis=0, arr=A)

array([13., 14., 15.])

In [7]:
np.apply_along_axis(np.mean, axis=1, arr=A)


array([11., 14., 17.])

In [9]:
def foo(x):
    return x / 2
np.apply_along_axis(foo, axis=1, arr=A)


array([[5, 5, 6],
       [6, 7, 7],
       [8, 8, 9]])

In [10]:
np.apply_along_axis(foo, axis=0, arr=A)


array([[5, 5, 6],
       [6, 7, 7],
       [8, 8, 9]])

In [11]:
A = np.random.random((4, 4))
A


array([[0.17292237, 0.17241149, 0.05235622, 0.92710538],
       [0.79445211, 0.4865951 , 0.53015279, 0.41859012],
       [0.19249103, 0.63155204, 0.07025385, 0.27901638],
       [0.19136002, 0.99993896, 0.88678915, 0.37500455]])

In [12]:
A < 0.5


array([[ True,  True,  True, False],
       [False,  True, False,  True],
       [ True, False,  True,  True],
       [ True, False, False,  True]])

In [13]:
A[A < 0.5]


array([0.17292237, 0.17241149, 0.05235622, 0.4865951 , 0.41859012,
       0.19249103, 0.07025385, 0.27901638, 0.19136002, 0.37500455])

In [14]:
a=np.random.random(12)

In [15]:
a

array([0.5727695 , 0.53074507, 0.79528478, 0.76259301, 0.46584825,
       0.92828459, 0.26258382, 0.08718578, 0.44838406, 0.32326774,
       0.88748011, 0.59746487])

In [18]:
A = a.reshape((3, 4))
A
a

array([0.5727695 , 0.53074507, 0.79528478, 0.76259301, 0.46584825,
       0.92828459, 0.26258382, 0.08718578, 0.44838406, 0.32326774,
       0.88748011, 0.59746487])

In [19]:
a.shape = (3, 4)
a

array([[0.5727695 , 0.53074507, 0.79528478, 0.76259301],
       [0.46584825, 0.92828459, 0.26258382, 0.08718578],
       [0.44838406, 0.32326774, 0.88748011, 0.59746487]])

In [27]:
a = a.ravel()
a.shape = (12)
a
A

array([[0.5727695 , 0.53074507, 0.79528478, 0.76259301],
       [0.46584825, 0.92828459, 0.26258382, 0.08718578],
       [0.44838406, 0.32326774, 0.88748011, 0.59746487]])

In [28]:
A.transpose()

array([[0.5727695 , 0.46584825, 0.44838406],
       [0.53074507, 0.92828459, 0.32326774],
       [0.79528478, 0.26258382, 0.88748011],
       [0.76259301, 0.08718578, 0.59746487]])

In [32]:
A = np.ones((3, 3))
B = np.zeros((3, 3))
np.vstack((A, B))
np.hstack((A, B))


array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [33]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])
np.column_stack((a, b, c))


array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [34]:
np.row_stack((a, b, c))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
[B, C] = np.hsplit(A, 2)
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [42]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [43]:
[B, C] = np.vsplit(A, 2)
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
[a, b, c] = np.split(A, [1, 3], axis=1)
a

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [47]:
b

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [48]:
c

array([[ 3],
       [ 7],
       [11],
       [15]])

In [60]:
[a, b, c] = np.split(A, [1, 2], axis=0)
a


array([[0, 1, 2, 3]])

In [61]:
b

array([[4, 5, 6, 7]])

In [62]:
c

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])